version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./public/images:/app/staycation-frontend/public/images
    environment:
      - PORT=3001
    restart: unless-stopped